version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nhannt
      POSTGRES_PASSWORD: nhannt-dev
      POSTGRES_DB: online_shop
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}